### ISSUE TITLE
Improving performances with screenrecorder native binary

### ISSUE THREAD

**Issue by AndreaCioccarelli** [afollestad/mnml#1]
Android natively supports screen recording using a built-in command line utility called "screenrecord"

![](https://i.imgur.com/HgKF2hI.jpg)

Shouldn't it be easier and improve performances to use it on devices supporting it? I believe that every lollipop installation comes with this built-in, but I'm not 100% sure.

If you notice in Android studio there is a "take video" or "take screenshot" button, in the logcat menu, that's how it works

**Comment by afollestad** [comment]
I don't think that would improve performance, and it would increase a lot of code complexity since output would have to be parsed, etc.
