### ISSUE TITLE
[OLD] Re-enable the recording resolution setting, and make it work

### ISSUE THREAD

**Issue by nubicoud** [afollestad/mnml#14]
---
name: Recording is always landscape
about: When trying to record, it will be always in landscape, even if the device is in vertical.
---

**Library Version:**

1.0.7
 
**Affected Device(s):**
 
Tested on a Moto G5 Plus on Android 9.0 (Pixel Experience ROM)
 
**Describe the Bug:**

Recording always goes landscape, even when trying to record in portrait. I added a video below (it is in a ZIP file because GitHub doesn't allow to upload MP4 files)
[MNML-December18-071635AM.zip](https://github.com/afollestad/mnml/files/2690852/MNML-December18-071635AM.zip)

**To Reproduce:**
1. Open MNML
2. Hit Record
3. Accept the "cast screen" dialog.
4. After some seconds of recording, stop the recording.

**Expected Behavior:**

If the device is vertical, record the screen in vertical.
If the device is horizontal, record the screen in horizontal.

**Comment by afollestad** [comment]
That sounds like a possible bug of the ROM 🤔

**Comment by reneantoniotg** [comment]
Just tried recording in 1080p (my screen resolution) and it works just fine.

The bug seems to happen on 720p.

**Comment by afollestad** [comment]
Closing in favor of https://github.com/afollestad/mnml/issues/17
