### ISSUE TITLE
Share isn't working with WhatsApp

### ISSUE THREAD

**Issue by bernaferrari** [afollestad/mnml#23]
This code, which I use on my apps, fixes it:

```kotlin
    val shareIntent = Intent(Intent.ACTION_SEND)
    shareIntent.type = "video/*"
    shareIntent.putExtra(Intent.EXTRA_STREAM, recording.toUri())
    shareIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
    startActivity(Intent.createChooser(shareIntent, getString(R.string.share)))
```

Also, small request: add the option to stop recording when countdown to start is running.

**Comment by afollestad** [comment]
`FLAG_GRANT_READ_URI_PERMISSION` shouldn't be necessary if you use a `FileProvider`

**Comment by bernaferrari** [comment]
Great, working fine now! I personally prefer the Intent.createChooser (shows recents and doesn't show the "just once"/"always" which I think is error prone), but it is working.

**Comment by bernaferrari** [comment]
You should also update it on other places, like notification.
