### ISSUE TITLE
Internal audio

### ISSUE THREAD

**Issue by hoyounglim43** [afollestad/mnml#25]
*Please consider making a Pull Request if you are capable of doing so.*

**What module does this apply to?**

Input?

**Description what you'd like to happen:**

I see that there is already an audio recording feature for while screen recording. I was wondering if you work be able to add a feature where it records the internal audio of whatever media is playing on the device itself.

**Describe alternatives you've considered:**

It's just a feature request. I love the work you are doing and the MNML app is the best I have ever seen. Keep up the good work my friend.

**Comment by afollestad** [comment]
There is no such thing on Android unfortunately. Unless you are rooted, I believe.
