### ISSUE TITLE
Don't allow inaccessible folders to be selected as the recording output folder

### ISSUE THREAD

**Issue by EyezGlazed** [afollestad/mnml#26]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

2.x.x
 
**Affected Device(s):**
 
Samsung S9+ with Android 8.0.0
 
**Describe the Bug:**

Shake or screen off not working ..so I can't record. It stops when I go in to the app (via notification bar where it shouldn't be in the first place according to the settings).. and doesn't save any recordings. I have accepted aii permissions (audio and storage and overlay).

**To Reproduce:**
1. 
2. 
3. 

**Expected Behavior:**

Stop recording and save recording

**Comment by afollestad** [comment]
There is a lot in this. What is the real issue? Stop to shake not working or recording not working in general? Those are two separate things.

**Comment by EyezGlazed** [comment]
It said it's recording, but the "stop" recording methods weren't working, so something crashed in the background it seems. Upon restarting the app, trying again, I got the following error:

"MNML was unable to access your file system. You may need to change your recording folder in MNML's settings. /storage/0000-0000/Screen Recordings/ 
MNML-January3-070702AM.mp4: open failed:
EACCES (Permission denied)"

Change location to "/sdcard/Screen Recordings" and now it works. Strange as my file explorer shows the first path as my sdcard and gives me access to it through that pathway.

**Comment by afollestad** [comment]
The output folder selector should only show accessible folders in the next release.
