### ISSUE TITLE
Host on F-Droid

### ISSUE THREAD

**Issue by IzzySoft** [afollestad/mnml#27]
Hi Aidan, would you consider offering an alternative download source for the APK – especially for folks without Playstore? For example, attaching the APK to its corresponding release? Or even bring it to F-Droid?

**Comment by afollestad** [comment]
Can't really do that - I'm using Android App Bundles so I don't generate APKs with releases and do not have a local keystore. Google does it on their backend.

**Comment by IzzySoft** [comment]
Ugh: you really trust Google with your signing key? :scream: I'd not be surprised if you find "unexpected ingredients" in your app on Play then one day.

Still, you can: Just say "yes, I'd appreciate that" – and I open an RFP at F-Droid for you. We build from the source ("May the source be with you"; disclosure: I'm one of the maintainers). So all we need is your "OK" (and maybe a little assistance in case problems should arise with the build).

So what d'you say? Deal? :smiley:

**Comment by afollestad** [comment]
So you're one of those people? Haha 😄it's definitely secure and lets you switch out signing keys without republishing your app. 

But if you can build from source that'd be great 👍 I'd appreciate it

**Comment by afollestad** [comment]
Good thing I got rid of Google Play Billing recently 😉

**Comment by IzzySoft** [comment]
Thanks, Aidan! [Opened the RFP](https://gitlab.com/fdroid/rfp/issues/860). Not sure if we can enable auto-update (as the gradle doesn't contain versionName/versionCode "literally") – but I leave that to one of our "integrators" to tell.

One thing you might wish to consider (just a suggestion – not a "hard requirement" but rather a "nice to have") is to use Fastlane/Triple-T for screenshots (plus optionally also description/summary, so you can maintain them yourself). See [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository) for details. That comes in handy for your Play publication as well.

> So you're one of those people?

I proudly admit, yes :rofl: Though not being an Android dev myself, there are tasks I can do. I mainly care for the metadata – e.g. that apps have good descriptions, the links are up-to-date, encourage devs, promote F-Droid – and [write articles on it](https://android.izzysoft.de/articles/named/fdroid-intro) including tutorials and more (that series started being printed in c't, one of Germany's top IT magazines – which is why the German variants are delayed; need to give the print a lead here).

> Good thing I got rid of Google Play Billing recently

Oh yes, definitely! :smile:

**Comment by IzzySoft** [comment]
Aidan: Our devs ask you to please not delete tags (causes confusion with our build system which will end in those releases being removed, if I understood correctly)? After all, they don't use space anyway :wink:

If you want to peek in: https://gitlab.com/fdroid/fdroiddata/merge_requests/4222 is  where integration is just being processed.

**Comment by afollestad** [comment]
Why would I delete tags here? Lol.

**Comment by afollestad** [comment]
No tags have been removed - this app is far too knew to even have a lot

**Comment by afollestad** [comment]
Oh, they're talking about Material Dialogs which is totally separate from this repository and shouldn't matter. Old tags were deleted when I was using JitPack to get rid of botched versions that were replaced. 

The newer version of Material Dialogs (2.0+) is a rewrite and doesn't using JitPack. Builds/tags are and will be persistent.

**Comment by IzzySoft** [comment]
As F-Droid needs to build *everything* from source, that also applies to the library. Don't ask me "deep technical details", I've got no clue about building apps :rofl: But well, when you say all will be persistent now: mission accomplished :smiley: 

Thanks!

**Comment by licaon-kter** [comment]
Any chance to add a non-closed source flavour? (ahem*non-Fabric*ahem)

Maybe that one can remove the useless INTERNET permission too...

**Comment by afollestad** [comment]
No, I'd rather not have a version with a lack of crash reporting in the wild.

**Comment by licaon-kter** [comment]
And ACRA is not good enugh?

**Comment by afollestad** [comment]
I don't want host a crash reporting server and Fabric's UI is superior.

**Comment by licaon-kter** [comment]
@afollestad ACRA will output a log that the user can send by email or whatever, if they wish.

**Comment by afollestad** [comment]
I definitely do not want manual report sending.

**Comment by licaon-kter** [comment]
And I hope you understand that F-Droid users might not want automatic report sending that they can't control or disable.

**Comment by afollestad** [comment]
Well others are welcome to contribute to this repo to add a flavor but I do not have any time to invest in supporting something that I will not use.
