### ISSUE TITLE
When Settings is opened and onRestart happens, it can't go back.

### ISSUE THREAD

**Issue by bernaferrari** [afollestad/mnml#31]
Steps to reproduce:
- Open Settings
- Close the app
- Open a lot of apps or open Android Studio and tap on that red square:
<img width="176" alt="screen shot 2019-01-06 at 00 48 26" src="https://user-images.githubusercontent.com/351125/50731476-cca40a00-114c-11e9-806e-60fad5688a5d.png">

- Open again

- Try pressing on back button (from Android) or on back button from app. Both will close it. If you re-open, settings view will be there again, until you force-close the app.

**Comment by afollestad** [comment]
Unable to reproduce - even with Don't Keep Activities enabled.

**Comment by bernaferrari** [comment]
This is still happening! I just recorded a video: https://photos.app.goo.gl/SfBuWW2t5xYCVRkd8
