### ISSUE TITLE
Force close when recording PUBG game 

### ISSUE THREAD

**Issue by Arockyfella** [afollestad/mnml#33]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

2.x.x
 
**Affected Device(s):**
 
Google Pixel 3 XL with Android 9.0
 
**Describe the Bug:**

A clear description of what is the bug is.

**To Reproduce:**
1. MNML v1.0.10
2. Nokia 6 2017 with Android 8.1
3. Force closes when trying to record PUBG gameplay 

**Expected Behavior:**
It is expected to record flawlessly without force closing... Thank you 
A clear description of what you expected to happen.

**Comment by afollestad** [comment]
Without a stack trace there isn't enough info here for a GitHub issue, unfortunately. I'll see what I can do from automatic crash reports though.
