### ISSUE TITLE
Bug.

### ISSUE THREAD

**Issue by shymonster** [afollestad/mnml#36]
*Please consider making a Pull Request if you are capable of doing so.* I would but don't see a way in settings

**Library Version:**

Newest release
 
**Affected Device(s):**
 
Lg stylus 4
 
**Describe the Bug:** 

A clear descript

**To Reproduce:**
1. Records but doesn't play
2. Phone won't play videos in the resolution
3. 

**Expected Behavior:**

I would expect it to play recorded videos.

**Comment by afollestad** [comment]
This isn't specific enough to be an issue here, or reproducible on my end.

**Comment by afollestad** [comment]
You may want to try changing quality settings like bit rate.

**Comment by shymonster** [comment]
Ah... Ya don't say, it's not like I'd try to figure it all out before
saying something. K thanks.
