### ISSUE TITLE
Crash when share is tapped 3 times

### ISSUE THREAD

**Issue by OVNIs** [afollestad/mnml#39]
[Error image](https://drive.google.com/file/d/11tzwoe-eEkvHeIJogEhX1Cs43R-60Vku/view?usp=drivesdk)
Closing when clicking three times on share.

**Comment by iambaji** [comment]
Can i work on this? I am a newbie, but from my understanding. on long press of recordings, the toolbar share controls are displayed and when i click "share" icon intent chooser is  opened then if the user clicks anywhere outside the intent chooser, the recording selection is getting erased but the share controls in toolbar are still visible(which is  not intended i think) and when i click the share icon with no recording selected(got erased earlier) . the result is the crash.
