### ISSUE TITLE
Floating controls?

### ISSUE THREAD

**Issue by afollestad** [afollestad/mnml#4]
A lot of recorder apps like to have floating controls. Thoughts:
1. It seems possibly redundant to the notification controls. 
2. This could increase the complexity of the app, not just code-wise, but from a UI/UX standpoint.

**Comment by AndreaCioccarelli** [comment]
Well I think that if this app is here is for maximum simplicity and straightforwardness, a floating control would not only make the registration unclear but also provide features that would be easily implementable in the notification.

Instead, a way to trim clips that have just been recorded (To remove for example frames where the notification is shown) would be very useful.

**Comment by searchy2** [comment]
How do apps implement floating controls without requesting "draw over other apps" while targeting Marshmallow and above <API 23?
For example, Facebook Messenger draws over other apps with their Chat Heads but no permission request is needed.

**Comment by afollestad** [comment]
@searchy2 the same APIs don't need that permission if the target SDK is lower than 23. Facebook gets around it by targeting an old version of Android.
