### ISSUE TITLE
Does not record in landscape orientation

### ISSUE THREAD

**Issue by cgjocson** [afollestad/mnml#40]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

2.x.x
 
**Affected Device(s):**
 
OnePlus 3T with Android 8.0.0
 
**Describe the Bug:**

I pressed "record" while the phone is held in landscape with the display also in landscape but the app recorded the screen as if it was in portrait orientation.

**To Reproduce:**
1. 
2. 
3. 

**Expected Behavior:**

I expected the app to record the screen in landscape orientation.

**Comment by afollestad** [comment]
29
