### ISSUE TITLE
Resolve my issue please

### ISSUE THREAD

**Issue by Devilsondhi** [afollestad/mnml#41]
Everything works fine .I am happy that it doesn't lag when I record PUBG Gameplay.The only issue I'm facing right now , is the resolution.please do something about it .I know you can do it.I will be best recorder on Playstore.

**Describe alternatives you've considered:**
There is one alternative present on Playstore,named as Screen recorder no ads .

**Comment by afollestad** [comment]
https://github.com/afollestad/mnml/issues/17
