### ISSUE TITLE
Videos don't play

### ISSUE THREAD

**Issue by Jormungandrrrr** [afollestad/mnml#43]
*Please fix the bug or better explain how to use the application*

 
**Affected Device(s):**
 
Infinix note 5 with Android 9
 
**Describe the Bug:**

Videos and recorded but do not play irregardless of the video players used to play it

**Expected Behavior:**

Video should play after recording

**Comment by realrufans** [comment]
I was able to reproduce this with Android Emulator (Android 9). but works fine with my physical device (Android 8.1).

**Comment by afollestad** [comment]
I suggest playing around with quality settings, I unfortunately won't be able to do much on my end as third party manufacturers sometimes mess up internal frameworks.
