### ISSUE TITLE
Bug: Automatic mode does not work

### ISSUE THREAD

**Issue by darewealth** [afollestad/mnml#44]
**Affected Device(s):**
 Itel mobile Android 6.1
 
**Describe the Bug:**
When the app automatic dark mode is set to a certain time, it does not work. I tried this multiple times, and I was facing the same issue.

**To Reproduce:**
1. Launch the app
2. Go to settings
3. Click on the UI 
4. Set the automatic mode and set time.

**Expected Behavior:**
I expected that the app should change to dark mode automatically when it reaches the time I set.

Recording Of The Bug
https://youtu.be/uDKLr7M6CcE

**Comment by afollestad** [comment]
You need to flip the top "Dark mode" switch, too. The automatic one alone doesn't do it.
