### ISSUE TITLE
Include GIF and Video to GIF converter 

### ISSUE THREAD

**Issue by darewealth** [afollestad/mnml#45]
I want to focus on additional means of recording which is **GIF**. **Gif** is a pure animated moving image known as ***Graphic interchange format***. I propose the addition of this format to the application. There could be a pop up when the record button is pressed that will ask the user if he/she wants to do ***Gif or Video.*** Users will decide the kind of format they want for themselves.

There could be a means within the application to **convert video to gif and verse visa**, which means if I record a screen movement in video and I later want it as GIF, this feature will allow me to do so. And, if I have a screen movement on GIF, I will be able to ***convert to MP4 for video*** players to play it. If the addition of gif can be added. The conversion would be another great addition.

## Mock up

The first image by the left side shows the current interface of the application, while the image on the right side shows the mock-up of my suggestion.
![](https://i.imgur.com/dT3kzZB.png)

I added a mock up Icon for the convertion of video to GIF. When the Icon is pressed, another page will show.
![](https://i.imgur.com/ipSUOQh.png)

This is the mock-up of the page that will show once the conversation  image is pressed, and it shows how it may look like when implemented.
![](https://i.imgur.com/S4n30of.png)

Gif is a very smooth way for screen recording. It takes less space on mobile, that means the size of gifs is usually lower than that of videos. In a scenario whereby video is not really needed the option will be handy. The conversion will be another great plus. Videos that are made before will be converted to gif without stress. The option will be very useful. There are situations whereby users will want to convert an existing video/Gif to another format like MP4. This will be a fast solution; there won't be a need to search for external applications.

Thank you

**Comment by afollestad** [comment]
I do not plan to include GIF conversion in the app as it would require a lot of custom code, and would add a lot of bulk to this app which I intend to keep very Minimal.
