### ISSUE TITLE
Feature request - internal sound source... And mixed... Mic and internal sound...

### ISSUE THREAD

**Issue by rakbar650** [afollestad/mnml#47]
very nice and simple app... working perfectly on my redmi note 4 Chinese version android 6.0... could you add internal sound option ? either without root or using root... since my android isn't nougat... oreo... nor pie... i think it is possible... thanks in advance !

**Comment by afollestad** [comment]
As the Play Store description and app state, that is not possible. There is no way to record internal audio.
