### ISSUE TITLE
Pause/Play

### ISSUE THREAD

**Issue by HairyChaka** [afollestad/mnml#49]
It would be nice to be able to pause and play on a screen recording, I know some people out there wouldn't mind having it. But I would enjoy it , because it's kind of like a "cut" if you will. An MMORPG game, RuneScape Mobile for example. You're at one location and don't want to make people watch the travel, you can pause, get to the next location and then play to resume recording.

**Comment by afollestad** [comment]
This is not easily possible without using third-party encoding, such as FFMPEG, which I don't have the time to implement or maintain.
