### ISSUE TITLE
Automatic night mode not working

### ISSUE THREAD

**Issue by cckole** [afollestad/mnml#53]
**Library Version:**

MNML v1.0.13
 
**Affected Device(s):**
 
Techno spark K7 with Android 7.0
 
**Describe the Bug:**

I set time for the app to automatically change to night mode when the time reaches, but at the stipulated time, there was no changes. It remains in day mode.

**To Reproduce:**
1. Launch the app
2. Click on the three dots(menu button) at the top right side
3. Click on settings
4. Click on UI
5. Turn on the Automatic dark mode
6. Set the dark mode start and start mode end and wait for the time.
7. Note if the default mode switch to dark mode when the set time reaches.

**Expected Behavior:**

After setting the time for the app to automatically change to dark mode, I expected it to change the moment the time reached.

**Reproducing the behavior**

https://youtu.be/MjSvlTPl_PE

Note the time at the top right side while watching the video and compare with the automatic time set. You will see that when the time reaches, there was no automatic change to dark mode.

**Comment by afollestad** [comment]
You need to turn on dark mode first.

**Comment by afollestad** [comment]
https://github.com/afollestad/mnml/issues/44

**Comment by cckole** [comment]
Perfect....

![Screenshot_20190521-041136](https://user-images.githubusercontent.com/36272218/58065833-ed5e8080-7b7e-11e9-8712-02b252ff0035.png)
Thanks.
