### ISSUE TITLE
Recording won't start if you go away from the app

### ISSUE THREAD

**Issue by Teeeemu** [afollestad/mnml#6]
When you go away from the app before the recording has started (the countdown phase) the app won't start recording.
This might be a bug - running on OP5T with Android Pie

**Comment by afollestad** [comment]
Hmmm - I'm unable to reproduce that on my Pixel 3 XL with Android Pie.  🤔

**Comment by Teeeemu** [comment]
Okay,
that might be also OnePlus' fault because my OP5T is running Open Beta Builds so they are a little bit unstable.

Thanks anyway for checking it with Pixel 3 XL!

**Comment by petitTrung** [comment]
I have the same oneplus 5t running the lastest Oxygen Oreo, i do not have any problem.
