### ISSUE TITLE
Icons in notifications doesn't show properly

### ISSUE THREAD

**Issue by milindgoel15** [afollestad/mnml#67]
Hi,
Not sure if this issue is known. 
But the icons in the notifications appears in white color, for example the buttons to start the recordings and cross button to stop the service. They appear white which result in non visibility of them. 
Plus these white icons only appears when system night mode is on. Else it works perfectly.

U can see the issue clearly here too
https://drive.google.com/file/d/0B_kKyQObxfRzdFlSdkt0NGlGWFFGMXhCSEctVlRVT3hQd084/view?usp=drivesdk

I also reported this through email given in play store. But no reply came so reporting here.

I hope u look into this issue. 
Thanks

**Comment by gkeegan** [comment]
I've noticed this as well. It seems like theming for the entire app is a little broken when theming the device itself.

**Comment by Jnss98b** [comment]
@milindgoel15 Just fyi, you can upload screenshots directly into the github issue tracker, no need to upload them to any cloud storage service

**Comment by milindgoel15** [comment]
@Jnss98b yea i wasn't able to upload at that time. 😅

**Comment by milindgoel15** [comment]
Rip mnml
